const axios = require('axios');

const MAILGUN_API_KEY = process.env.MAILGUN_API_KEY;
const MAILGUN_API_BASE = 'https://api.mailgun.net/v3';

const auth = {
  username: 'api',
  password: MAILGUN_API_KEY
};

// Function to Add Domain to Mailgun
async function addDomain(domain) {
  const response = await axios.post(
    `${MAILGUN_API_BASE}/domains`,
    new URLSearchParams({
      name: domain,
      smtp_password: 'autoGeneratedPass',
      spam_action: 'disabled',
      wildcard: true
    }),
    { auth }
  );

  return response.data;
}

module.exports = { addDomain };
